# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
hand_controller:
  ros__parameters:
    joints:
      - r_indexMCP
      - r_indexPIP
      - r_littleMCP
      - r_littlePIP
      - r_middleMCP
      - r_middlePIP
      - r_ringMCP
      - r_ringPIP
      - r_thumbCMC
      - r_thumbMCP
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity