# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - joint_trajectory_controller
    - hand_controller
    - scaled_joint_trajectory_controller

  joint_trajectory_controller:
    type: FollowJointTrajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    action_ns: follow_joint_trajectory
    default: true
  hand_controller:
    type: FollowJointTrajectory
    joints:
      - r_indexMCP
      - r_indexPIP
      - r_littleMCP
      - r_littlePIP
      - r_middleMCP
      - r_middlePIP
      - r_ringMCP
      - r_ringPIP
      - r_thumbCMC
      - r_thumbMCP
    action_ns: follow_joint_trajectory
    default: true
  scaled_joint_trajectory_controller:
    type: FollowJointTrajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    action_ns: follow_joint_trajectory
    default: false